data:
    image: silintl/data-volume:latest
    volumes:
        - /data:/data
db:
    image: silintl/mariadb:latest
    ports:
        - "3306"
    environment:
        MYSQL_ROOT_PASSWORD: r00tp@ss!
        MYSQL_DATABASE: appbuilder
        MYSQL_USER: appbuilder
        MYSQL_PASSWORD: appbuilder
web:
    build: .
    volumes_from:
        - data
    ports:
        - "80:80"
    links:
        - db
    env_file:
        - ./common.env
        - ./local.env
cron:
    build: .
    volumes_from:
        - data
    links:
        - db
    env_file:
        - ./common.env
        - ./local.env
    environment:
        - "EXPAND_S3_KEY=AKIAJLPR4553Z5ZURUFQ"
        - "EXPAND_S3_SECRET=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"
        - "EXPAND_S3_FILES=sil-appbuilder-secrets/staging/buildengine_api/ssh/id_rsa|/root/.ssh/id_rsa[600,] sil-appbuilder-secrets/staging/buildengine_api/ssh/id_rsa.pub|/root/.ssh/id_rsa.pub[600,]"
    command: /data/run-cron.sh
composer:
    image: silintl/php-cli:latest
    volumes_from:
        - data
    working_dir: /data
    command: composer install --prefer-dist
yiimigrate:
    image: silintl/php-cli:latest
    volumes_from:
        - data
    links:
        - db
    env_file:
        - ./common.env
        - ./local.env
    working_dir: /data
    command: bash -c "whenavail db 3306 100 ./yii migrate --interactive=0 && ./rebuildbasemodels.sh"
